version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "postgres:11-alpine"
    environment:
      - POSTGRES_PASSWORD=billing-task
      - POSTGRES_DB=billing-task
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 3s
      retries: 10
    volumes:
    - ./sql/tables.sql:/docker-entrypoint-initdb.d/init.sql
